@startuml

title __COMPOSITELEAFOBSERVEDBYCOMPOSITE's Class Diagram__\n

  namespace is.hi.hbv202g.ass9 {
    namespace composite {
      namespace eafObservedByComposite {
        interface is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Component {
            {abstract} + getResult()
        }
      }
    }
  }
  

  namespace is.hi.hbv202g.ass9 {
    namespace composite {
      namespace eafObservedByComposite {
        class is.hi.hbv202g.ass9.compositeLeafObservedByComposite.MultiplyComposite {
            - children : ArrayList<Component>
            - lastObservedResult : int
            + add()
            + getLastObservedResult()
            + getResult()
            + update()
        }
      }
    }
  }
  

  namespace is.hi.hbv202g.ass9 {
    namespace composite {
      namespace eafObservedByComposite {
        class is.hi.hbv202g.ass9.compositeLeafObservedByComposite.NumberLeaf {
            - number : int
            + NumberLeaf()
            + getResult()
            + setValue()
        }
      }
    }
  }
  

  namespace is.hi.hbv202g.ass9 {
    namespace composite {
      namespace eafObservedByComposite {
        abstract class is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Observable {
            - observers : List<Observer>
            + Observable()
            + attach()
            + detachObserver()
            + notifyObservers()
        }
      }
    }
  }
  

  namespace is.hi.hbv202g.ass9 {
    namespace composite {
      namespace eafObservedByComposite {
        interface is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Observer {
            {abstract} + update()
        }
      }
    }
  }
  

  namespace is.hi.hbv202g.ass9 {
    namespace composite {
      namespace eafObservedByComposite {
        class is.hi.hbv202g.ass9.compositeLeafObservedByComposite.PlusComposite {
            - children : ArrayList<Component>
            - lastObservedResult : int
            + add()
            + getLastObservedResult()
            + getResult()
            + update()
        }
      }
    }
  }
  

  is.hi.hbv202g.ass9.compositeLeafObservedByComposite.MultiplyComposite .up.|> is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Component
  is.hi.hbv202g.ass9.compositeLeafObservedByComposite.MultiplyComposite .up.|> is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Observer
  is.hi.hbv202g.ass9.compositeLeafObservedByComposite.NumberLeaf .up.|> is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Component
  is.hi.hbv202g.ass9.compositeLeafObservedByComposite.NumberLeaf -up-|> is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Observable
  is.hi.hbv202g.ass9.compositeLeafObservedByComposite.PlusComposite .up.|> is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Component
  is.hi.hbv202g.ass9.compositeLeafObservedByComposite.PlusComposite .up.|> is.hi.hbv202g.ass9.compositeLeafObservedByComposite.Observer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
